export const FORMULARIO_TODOLIST = "FORMULARIO_TODOLIST";
export const OBTENER_TODOLISTS = "OBTENER_TODOLISTS";
export const AGREGAR_TODOLIST = "AGREGAR_TODOLIST";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
export const TODOLIST_ACTUAL = "TODOLIST_ACTUAL";
export const ELIMINAR_TODOLIST = "ELIMINAR_TODOLIST";
export const TODOLIST_ERROR = "TODOLIST_ERROR";

export const TASKS_TODOLIST = "TASKS_TODOLIST";
export const AGREGAR_TASK = "AGREGAR_TASK";
export const VALIDAR_TASK = "VALIDAR_TASK";
export const ELIMINAR_TASK = "ELIMINAR_TASK";
export const TASK_ACTUAL = "TASK_ACTUAL";
export const ACTUALIZAR_TASK = "ACTUALIZAR_TASK";
export const LIMPIAR_TASK = "LIMPIAR_TASK";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
